### ISSUE TITLE
Fails with directory which doesn't exist

### ISSUE THREAD

**Issue by sarkarshuvojit** [sarkarshuvojit/webhook-load-tester#8]
Following config provided that the reports dir doesn't exist currently, will throw an error "no such file or directory"

```yaml
...
outputs:
  - type: text
    path: reports/gg-250i-10s.txt
...
```

It should create the said dir if it already doesn't exist
